//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hranitel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zayavki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zayavki()
        {
            this.InformationAboutTourists = new HashSet<InformationAboutTourist>();
        }
    
        public int id { get; set; }
        public Nullable<int> IdDefUsers { get; set; }
        public Nullable<int> IdUsers { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> Dates { get; set; }
        public string Status { get; set; }
        public Nullable<int> Cel { get; set; }
    
        public virtual CelPos CelPos { get; set; }
        public virtual DefUser DefUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformationAboutTourist> InformationAboutTourists { get; set; }
        public virtual TypeZayavk TypeZayavk { get; set; }
        public virtual User User { get; set; }
    }
}
